/**
 * Auto-generated route helpers — do not edit.
 * Generated by Innovation.TsGen
 */

export interface RouteDefinition<M extends string = string> {
    url: string;
    method: M;
}

/** @controller AuthApiProxy @action Login @route '/api/auth/login' */
export const login = (): RouteDefinition<'post'> => ({
    url: '/api/auth/login',
    method: 'post',
})

login.url = () => '/api/auth/login'

/** @controller AuthApiProxy @action Logout @route '/api/auth/logout' */
export const logout = (): RouteDefinition<'post'> => ({
    url: '/api/auth/logout',
    method: 'post',
})

logout.url = () => '/api/auth/logout'

/** @controller AuthApiProxy @action Me @route '/api/auth/me' */
export const me = (): RouteDefinition<'get'> => ({
    url: '/api/auth/me',
    method: 'get',
})

me.url = () => '/api/auth/me'

/** @controller AuthApiProxy @action Register @route '/api/auth/register' */
export const register = (): RouteDefinition<'post'> => ({
    url: '/api/auth/register',
    method: 'post',
})

register.url = () => '/api/auth/register'

