/**
 * Auto-generated route helpers — do not edit.
 * Generated by Innovation.TsGen
 */

export interface RouteDefinition<M extends string = string> {
    url: string;
    method: M;
}

/** @controller Role @action list @route '/api/roles' @method get */
export const list = (): RouteDefinition<'get'> => ({
    url: '/api/roles',
    method: 'get',
})

list.url = () => '/api/roles'

/** @controller Role @action create @route '/api/roles' @method post */
export const create = (): RouteDefinition<'post'> => ({
    url: '/api/roles',
    method: 'post',
})

create.url = () => '/api/roles'

/** @controller Role @action get @route '/api/roles/{id}' @method get */
export const get = (args: { id: string | number }): RouteDefinition<'get'> => ({
    url: `/api/roles/${args.id}`,
    method: 'get',
})

get.url = (args: { id: string | number }) => `/api/roles/${args.id}`

/** @controller Role @action update @route '/api/roles/{id}' @method put */
export const update = (args: { id: string | number }): RouteDefinition<'put'> => ({
    url: `/api/roles/${args.id}`,
    method: 'put',
})

update.url = (args: { id: string | number }) => `/api/roles/${args.id}`

/** @controller Role @action remove @route '/api/roles/{id}' @method delete */
export const remove = (args: { id: string | number }): RouteDefinition<'delete'> => ({
    url: `/api/roles/${args.id}`,
    method: 'delete',
})

remove.url = (args: { id: string | number }) => `/api/roles/${args.id}`

/** @controller Role @action assign @route '/api/roles/assign' @method post */
export const assign = (): RouteDefinition<'post'> => ({
    url: '/api/roles/assign',
    method: 'post',
})

assign.url = () => '/api/roles/assign'

/** @controller Role @action sync @route '/api/roles/sync' @method post */
export const sync = (): RouteDefinition<'post'> => ({
    url: '/api/roles/sync',
    method: 'post',
})

sync.url = () => '/api/roles/sync'

