/**
 * Auto-generated filter/sort definitions — do not edit.
 * Generated by Innovation.TsGen
 */

export interface GridifyQuery {
  page?: number;
  pageSize?: number;
  orderBy?: string | null;
  filter?: string | null;
}

export type FilterOperator = '=' | '!=' | '<' | '>' | '<=' | '>=' | '=*' | '!*' | '^' | '!^' | '$' | '!$';

// Challenge filterable/sortable fields
export const challengeFields = [
  'title',
  'titleAr',
  'status',
  'difficulty',
  'featured',
  'urgent',
  'isPublic',
  'startDate',
  'endDate',
  'createdAt',
  'categoryId',
] as const;

export type ChallengeField = typeof challengeFields[number];

export type ChallengeOrderBy = `${ChallengeField} asc` | `${ChallengeField} desc`;

export const challengeDefaultOrderBy = 'createdAt desc';

// Filter builder helpers
export function filter<F extends string>(field: F, op: FilterOperator, value: string | number | boolean): string {
  return `${field}${op}${value}`;
}

export function and(...filters: string[]): string {
  return filters.join(',');
}

export function or(...filters: string[]): string {
  return filters.join('|');
}

