//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export interface ITranslatableString
{
	en?: string;
	ar?: string;
}
export interface IAuthUser
{
	id: string;
	name: string;
	email: string;
}
export interface IAuthProps
{
	user?: IAuthUser;
}
export interface ISharedProps
{
	auth: IAuthProps;
}
export enum ChallengeStatus {
	Draft = 0,
	Upcoming = 1,
	Open = 2,
	Closed = 3,
	Judging = 4,
	Voting = 5,
	Completed = 6,
	Cancelled = 7
}
