/**
 * Auto-generated permission types — do not edit.
 * Generated by Innovation.TsGen
 */

export type Permission =
    | 'admin:dashboard:summary'
    | 'admin:dashboard:analytics'
    | 'admin:dashboard:financial'
    | 'admin:dashboard:reports'
    | 'admin:users:create'
    | 'admin:users:read'
    | 'admin:users:update'
    | 'admin:users:delete'
    | 'admin:users:forceDelete'
    | 'admin:users:restore'
    | 'admin:users:export'
    | 'admin:users:import'
    | 'admin:roles:create'
    | 'admin:roles:read'
    | 'admin:roles:update'
    | 'admin:roles:delete'
    | 'admin:roles:assign'
    | 'admin:permissions:create'
    | 'admin:permissions:read'
    | 'admin:permissions:update'
    | 'admin:permissions:delete'
    | 'admin:permissions:assign'
    | 'admin:admins:create'
    | 'admin:admins:read'
    | 'admin:admins:update'
    | 'admin:admins:delete'
    | 'admin:admins:forceDelete'
    | 'admin:admins:restore'
    | 'admin:challenges:create'
    | 'admin:challenges:read'
    | 'admin:challenges:update'
    | 'admin:challenges:delete'
    | 'admin:challenges:forceDelete'
    | 'admin:challenges:restore'
    | 'admin:challenges:publish'
    | 'admin:challenges:unpublish'
    | 'admin:challenges:approve'
    | 'admin:challenges:reject'
    | 'admin:challenge_mentors:create'
    | 'admin:challenge_mentors:read'
    | 'admin:challenge_mentors:update'
    | 'admin:challenge_mentors:delete'
    | 'admin:challenge_mentors:assign'
    | 'admin:challenge_sponsors:create'
    | 'admin:challenge_sponsors:read'
    | 'admin:challenge_sponsors:update'
    | 'admin:challenge_sponsors:delete'
    | 'admin:challenge_requirements:create'
    | 'admin:challenge_requirements:read'
    | 'admin:challenge_requirements:update'
    | 'admin:challenge_requirements:delete'
    | 'admin:challenge_objectives:create'
    | 'admin:challenge_objectives:read'
    | 'admin:challenge_objectives:update'
    | 'admin:challenge_objectives:delete'
    | 'admin:challenge_risks:create'
    | 'admin:challenge_risks:read'
    | 'admin:challenge_risks:update'
    | 'admin:challenge_risks:delete'
    | 'admin:challenge_timelines:create'
    | 'admin:challenge_timelines:read'
    | 'admin:challenge_timelines:update'
    | 'admin:challenge_timelines:delete'
    | 'admin:ideas:create'
    | 'admin:ideas:read'
    | 'admin:ideas:update'
    | 'admin:ideas:delete'
    | 'admin:ideas:forceDelete'
    | 'admin:ideas:restore'
    | 'admin:ideas:approve'
    | 'admin:ideas:reject'
    | 'admin:ideas:evaluate'
    | 'admin:idea_steps:create'
    | 'admin:idea_steps:read'
    | 'admin:idea_steps:update'
    | 'admin:idea_steps:delete'
    | 'admin:idea_team_members:create'
    | 'admin:idea_team_members:read'
    | 'admin:idea_team_members:update'
    | 'admin:idea_team_members:delete'
    | 'admin:idea_evaluators:create'
    | 'admin:idea_evaluators:read'
    | 'admin:idea_evaluators:update'
    | 'admin:idea_evaluators:delete'
    | 'admin:idea_evaluators:assign'
    | 'admin:idea_methodologies:create'
    | 'admin:idea_methodologies:read'
    | 'admin:idea_methodologies:update'
    | 'admin:idea_methodologies:delete'
    | 'admin:innovation_types:create'
    | 'admin:innovation_types:read'
    | 'admin:innovation_types:update'
    | 'admin:innovation_types:delete'
    | 'admin:innovation_methodologies:create'
    | 'admin:innovation_methodologies:read'
    | 'admin:innovation_methodologies:update'
    | 'admin:innovation_methodologies:delete'
    | 'admin:evaluation_templates:create'
    | 'admin:evaluation_templates:read'
    | 'admin:evaluation_templates:update'
    | 'admin:evaluation_templates:delete'
    | 'admin:evaluation_stages:create'
    | 'admin:evaluation_stages:read'
    | 'admin:evaluation_stages:update'
    | 'admin:evaluation_stages:delete'
    | 'admin:evaluation_factors:create'
    | 'admin:evaluation_factors:read'
    | 'admin:evaluation_factors:update'
    | 'admin:evaluation_factors:delete'
    | 'admin:evaluation_factor_items:create'
    | 'admin:evaluation_factor_items:read'
    | 'admin:evaluation_factor_items:update'
    | 'admin:evaluation_factor_items:delete'
    | 'admin:evaluation_factor_specialties:create'
    | 'admin:evaluation_factor_specialties:read'
    | 'admin:evaluation_factor_specialties:update'
    | 'admin:evaluation_factor_specialties:delete'
    | 'admin:evaluation_factor_specialties:assign'
    | 'admin:evaluation_factor_stages:create'
    | 'admin:evaluation_factor_stages:read'
    | 'admin:evaluation_factor_stages:update'
    | 'admin:evaluation_factor_stages:delete'
    | 'admin:evaluation_assessment_values:create'
    | 'admin:evaluation_assessment_values:read'
    | 'admin:evaluation_assessment_values:update'
    | 'admin:evaluation_assessment_values:delete'
    | 'admin:evaluation_assessment_recommendations:create'
    | 'admin:evaluation_assessment_recommendations:read'
    | 'admin:evaluation_assessment_recommendations:update'
    | 'admin:evaluation_assessment_recommendations:delete'
    | 'admin:jury_members:create'
    | 'admin:jury_members:read'
    | 'admin:jury_members:update'
    | 'admin:jury_members:delete'
    | 'admin:jury_members:assign'
    | 'admin:comments:create'
    | 'admin:comments:read'
    | 'admin:comments:update'
    | 'admin:comments:delete'
    | 'admin:comments:moderate'
    | 'admin:likes:create'
    | 'admin:likes:read'
    | 'admin:likes:delete'
    | 'admin:bookmarks:create'
    | 'admin:bookmarks:read'
    | 'admin:bookmarks:delete'
    | 'admin:attachments:create'
    | 'admin:attachments:read'
    | 'admin:attachments:update'
    | 'admin:attachments:delete'
    | 'admin:attachments:download'
    | 'admin:issue_reports:create'
    | 'admin:issue_reports:read'
    | 'admin:issue_reports:update'
    | 'admin:issue_reports:delete'
    | 'admin:issue_reports:resolve'
    | 'admin:user_profiles:read'
    | 'admin:user_profiles:update'
    | 'admin:user_profiles:delete'
    | 'admin:user_specialties:read'
    | 'admin:user_specialties:update'
    | 'admin:user_specialties:assign'
    | 'admin:user_specialties:revoke'
    | 'admin:settings:read'
    | 'admin:settings:update'
    | 'admin:audit_logs:read'
    | 'admin:audit_logs:export'
    | 'admin:notifications:create'
    | 'admin:notifications:read'
    | 'admin:notifications:update'
    | 'admin:notifications:delete'
    | 'admin:notifications:send'
    | 'admin:translations:read'
    | 'admin:translations:update'
    | 'admin:backups:create'
    | 'admin:backups:read'
    | 'admin:backups:download'
    | 'admin:backups:restore'
    | 'admin:cache:clear'
    | 'admin:maintenance:enable'
    | 'admin:maintenance:disable'
    | 'admin:panel_access'
    | 'admin:view_statistics'
    | 'admin:export_data'
    | 'admin:import_data'
    | 'admin:bulk_actions'
    | 'admin:impersonate_users'
    | 'admin:manage_settings'
    | 'admin:view_system_info'
    | 'admin:manage_integrations'
    | 'user:challenges:read'
    | 'user:challenges:participate'
    | 'user:challenges:submit'
    | 'user:ideas:create'
    | 'user:ideas:read'
    | 'user:ideas:update'
    | 'user:ideas:delete'
    | 'user:ideas:submit'
    | 'user:comments:create'
    | 'user:comments:read'
    | 'user:comments:update'
    | 'user:comments:delete'
    | 'user:likes:create'
    | 'user:likes:delete'
    | 'user:bookmarks:create'
    | 'user:bookmarks:read'
    | 'user:bookmarks:delete'
    | 'user:attachments:create'
    | 'user:attachments:read'
    | 'user:attachments:delete'
    | 'user:attachments:download'
    | 'user:issue_reports:create'
    | 'user:issue_reports:read'
    | 'user:user_profiles:read'
    | 'user:user_profiles:update'
    | 'user:view_own_submissions'
    | 'user:edit_own_submissions'
    | 'user:delete_own_submissions'
    | 'user:view_public_content'
    | 'user:participate_in_challenges'
    | 'user:submit_ideas'
    | 'user:vote'
    | 'user:comment'
    | 'user:upload_files'
    | 'evaluator:ideas:read'
    | 'evaluator:ideas:evaluate'
    | 'evaluator:evaluation_assessment_values:create'
    | 'evaluator:evaluation_assessment_values:read'
    | 'evaluator:evaluation_assessment_values:update'
    | 'evaluator:evaluation_assessment_recommendations:create'
    | 'evaluator:evaluation_assessment_recommendations:read'
    | 'evaluator:evaluation_assessment_recommendations:update'
    | 'evaluator:comments:create'
    | 'evaluator:comments:read'
    | 'evaluator:evaluate_ideas'
    | 'evaluator:submit_assessments'
    | 'evaluator:view_assigned_ideas'
    | 'evaluator:provide_recommendations'
    | 'jury:ideas:read'
    | 'jury:ideas:evaluate'
    | 'jury:ideas:score'
    | 'jury:challenges:read'
    | 'jury:evaluation_stages:read'
    | 'jury:final_evaluation'
    | 'jury:select_winners'
    | 'jury:view_all_submissions'
    | 'jury:access_jury_panel'
    | 'mentor:challenges:read'
    | 'mentor:challenges:mentor'
    | 'mentor:ideas:read'
    | 'mentor:ideas:guide'
    | 'mentor:comments:create'
    | 'mentor:comments:read'
    | 'mentor:mentor_participants'
    | 'mentor:provide_guidance'
    | 'mentor:view_assigned_challenges';

export type UserType =
    | 'admin'
    | 'evaluator'
    | 'jury'
    | 'mentor'
    | 'super-admin'
    | 'user';

export const permissionGroups: Record<string, readonly Permission[]> = {
    'admin': [
        'admin:admins:create',
        'admin:admins:delete',
        'admin:admins:forceDelete',
        'admin:admins:read',
        'admin:admins:restore',
        'admin:admins:update',
        'admin:attachments:create',
        'admin:attachments:delete',
        'admin:attachments:download',
        'admin:attachments:read',
        'admin:attachments:update',
        'admin:audit_logs:export',
        'admin:audit_logs:read',
        'admin:backups:create',
        'admin:backups:download',
        'admin:backups:read',
        'admin:backups:restore',
        'admin:bookmarks:create',
        'admin:bookmarks:delete',
        'admin:bookmarks:read',
        'admin:bulk_actions',
        'admin:cache:clear',
        'admin:challenge_mentors:assign',
        'admin:challenge_mentors:create',
        'admin:challenge_mentors:delete',
        'admin:challenge_mentors:read',
        'admin:challenge_mentors:update',
        'admin:challenge_objectives:create',
        'admin:challenge_objectives:delete',
        'admin:challenge_objectives:read',
        'admin:challenge_objectives:update',
        'admin:challenge_requirements:create',
        'admin:challenge_requirements:delete',
        'admin:challenge_requirements:read',
        'admin:challenge_requirements:update',
        'admin:challenge_risks:create',
        'admin:challenge_risks:delete',
        'admin:challenge_risks:read',
        'admin:challenge_risks:update',
        'admin:challenge_sponsors:create',
        'admin:challenge_sponsors:delete',
        'admin:challenge_sponsors:read',
        'admin:challenge_sponsors:update',
        'admin:challenge_timelines:create',
        'admin:challenge_timelines:delete',
        'admin:challenge_timelines:read',
        'admin:challenge_timelines:update',
        'admin:challenges:approve',
        'admin:challenges:create',
        'admin:challenges:delete',
        'admin:challenges:forceDelete',
        'admin:challenges:publish',
        'admin:challenges:read',
        'admin:challenges:reject',
        'admin:challenges:restore',
        'admin:challenges:unpublish',
        'admin:challenges:update',
        'admin:comments:create',
        'admin:comments:delete',
        'admin:comments:moderate',
        'admin:comments:read',
        'admin:comments:update',
        'admin:dashboard:analytics',
        'admin:dashboard:financial',
        'admin:dashboard:reports',
        'admin:dashboard:summary',
        'admin:evaluation_assessment_recommendations:create',
        'admin:evaluation_assessment_recommendations:delete',
        'admin:evaluation_assessment_recommendations:read',
        'admin:evaluation_assessment_recommendations:update',
        'admin:evaluation_assessment_values:create',
        'admin:evaluation_assessment_values:delete',
        'admin:evaluation_assessment_values:read',
        'admin:evaluation_assessment_values:update',
        'admin:evaluation_factor_items:create',
        'admin:evaluation_factor_items:delete',
        'admin:evaluation_factor_items:read',
        'admin:evaluation_factor_items:update',
        'admin:evaluation_factor_specialties:assign',
        'admin:evaluation_factor_specialties:create',
        'admin:evaluation_factor_specialties:delete',
        'admin:evaluation_factor_specialties:read',
        'admin:evaluation_factor_specialties:update',
        'admin:evaluation_factor_stages:create',
        'admin:evaluation_factor_stages:delete',
        'admin:evaluation_factor_stages:read',
        'admin:evaluation_factor_stages:update',
        'admin:evaluation_factors:create',
        'admin:evaluation_factors:delete',
        'admin:evaluation_factors:read',
        'admin:evaluation_factors:update',
        'admin:evaluation_stages:create',
        'admin:evaluation_stages:delete',
        'admin:evaluation_stages:read',
        'admin:evaluation_stages:update',
        'admin:evaluation_templates:create',
        'admin:evaluation_templates:delete',
        'admin:evaluation_templates:read',
        'admin:evaluation_templates:update',
        'admin:export_data',
        'admin:idea_evaluators:assign',
        'admin:idea_evaluators:create',
        'admin:idea_evaluators:delete',
        'admin:idea_evaluators:read',
        'admin:idea_evaluators:update',
        'admin:idea_methodologies:create',
        'admin:idea_methodologies:delete',
        'admin:idea_methodologies:read',
        'admin:idea_methodologies:update',
        'admin:idea_steps:create',
        'admin:idea_steps:delete',
        'admin:idea_steps:read',
        'admin:idea_steps:update',
        'admin:idea_team_members:create',
        'admin:idea_team_members:delete',
        'admin:idea_team_members:read',
        'admin:idea_team_members:update',
        'admin:ideas:approve',
        'admin:ideas:create',
        'admin:ideas:delete',
        'admin:ideas:evaluate',
        'admin:ideas:forceDelete',
        'admin:ideas:read',
        'admin:ideas:reject',
        'admin:ideas:restore',
        'admin:ideas:update',
        'admin:impersonate_users',
        'admin:import_data',
        'admin:innovation_methodologies:create',
        'admin:innovation_methodologies:delete',
        'admin:innovation_methodologies:read',
        'admin:innovation_methodologies:update',
        'admin:innovation_types:create',
        'admin:innovation_types:delete',
        'admin:innovation_types:read',
        'admin:innovation_types:update',
        'admin:issue_reports:create',
        'admin:issue_reports:delete',
        'admin:issue_reports:read',
        'admin:issue_reports:resolve',
        'admin:issue_reports:update',
        'admin:jury_members:assign',
        'admin:jury_members:create',
        'admin:jury_members:delete',
        'admin:jury_members:read',
        'admin:jury_members:update',
        'admin:likes:create',
        'admin:likes:delete',
        'admin:likes:read',
        'admin:maintenance:disable',
        'admin:maintenance:enable',
        'admin:manage_integrations',
        'admin:manage_settings',
        'admin:notifications:create',
        'admin:notifications:delete',
        'admin:notifications:read',
        'admin:notifications:send',
        'admin:notifications:update',
        'admin:panel_access',
        'admin:permissions:assign',
        'admin:permissions:create',
        'admin:permissions:delete',
        'admin:permissions:read',
        'admin:permissions:update',
        'admin:roles:assign',
        'admin:roles:create',
        'admin:roles:delete',
        'admin:roles:read',
        'admin:roles:update',
        'admin:settings:read',
        'admin:settings:update',
        'admin:translations:read',
        'admin:translations:update',
        'admin:user_profiles:delete',
        'admin:user_profiles:read',
        'admin:user_profiles:update',
        'admin:user_specialties:assign',
        'admin:user_specialties:read',
        'admin:user_specialties:revoke',
        'admin:user_specialties:update',
        'admin:users:create',
        'admin:users:delete',
        'admin:users:export',
        'admin:users:forceDelete',
        'admin:users:import',
        'admin:users:read',
        'admin:users:restore',
        'admin:users:update',
        'admin:view_statistics',
        'admin:view_system_info',
    ],
    'evaluator': [
        'evaluator:comments:create',
        'evaluator:comments:read',
        'evaluator:evaluate_ideas',
        'evaluator:evaluation_assessment_recommendations:create',
        'evaluator:evaluation_assessment_recommendations:read',
        'evaluator:evaluation_assessment_recommendations:update',
        'evaluator:evaluation_assessment_values:create',
        'evaluator:evaluation_assessment_values:read',
        'evaluator:evaluation_assessment_values:update',
        'evaluator:ideas:evaluate',
        'evaluator:ideas:read',
        'evaluator:provide_recommendations',
        'evaluator:submit_assessments',
        'evaluator:view_assigned_ideas',
    ],
    'jury': [
        'jury:access_jury_panel',
        'jury:challenges:read',
        'jury:evaluation_stages:read',
        'jury:final_evaluation',
        'jury:ideas:evaluate',
        'jury:ideas:read',
        'jury:ideas:score',
        'jury:select_winners',
        'jury:view_all_submissions',
    ],
    'mentor': [
        'mentor:challenges:mentor',
        'mentor:challenges:read',
        'mentor:comments:create',
        'mentor:comments:read',
        'mentor:ideas:guide',
        'mentor:ideas:read',
        'mentor:mentor_participants',
        'mentor:provide_guidance',
        'mentor:view_assigned_challenges',
    ],
    'user': [
        'user:attachments:create',
        'user:attachments:delete',
        'user:attachments:download',
        'user:attachments:read',
        'user:bookmarks:create',
        'user:bookmarks:delete',
        'user:bookmarks:read',
        'user:challenges:participate',
        'user:challenges:read',
        'user:challenges:submit',
        'user:comment',
        'user:comments:create',
        'user:comments:delete',
        'user:comments:read',
        'user:comments:update',
        'user:delete_own_submissions',
        'user:edit_own_submissions',
        'user:ideas:create',
        'user:ideas:delete',
        'user:ideas:read',
        'user:ideas:submit',
        'user:ideas:update',
        'user:issue_reports:create',
        'user:issue_reports:read',
        'user:likes:create',
        'user:likes:delete',
        'user:participate_in_challenges',
        'user:submit_ideas',
        'user:upload_files',
        'user:user_profiles:read',
        'user:user_profiles:update',
        'user:view_own_submissions',
        'user:view_public_content',
        'user:vote',
    ],
} as const;

export const allPermissions: readonly Permission[] = [
    'admin:dashboard:summary',
    'admin:dashboard:analytics',
    'admin:dashboard:financial',
    'admin:dashboard:reports',
    'admin:users:create',
    'admin:users:read',
    'admin:users:update',
    'admin:users:delete',
    'admin:users:forceDelete',
    'admin:users:restore',
    'admin:users:export',
    'admin:users:import',
    'admin:roles:create',
    'admin:roles:read',
    'admin:roles:update',
    'admin:roles:delete',
    'admin:roles:assign',
    'admin:permissions:create',
    'admin:permissions:read',
    'admin:permissions:update',
    'admin:permissions:delete',
    'admin:permissions:assign',
    'admin:admins:create',
    'admin:admins:read',
    'admin:admins:update',
    'admin:admins:delete',
    'admin:admins:forceDelete',
    'admin:admins:restore',
    'admin:challenges:create',
    'admin:challenges:read',
    'admin:challenges:update',
    'admin:challenges:delete',
    'admin:challenges:forceDelete',
    'admin:challenges:restore',
    'admin:challenges:publish',
    'admin:challenges:unpublish',
    'admin:challenges:approve',
    'admin:challenges:reject',
    'admin:challenge_mentors:create',
    'admin:challenge_mentors:read',
    'admin:challenge_mentors:update',
    'admin:challenge_mentors:delete',
    'admin:challenge_mentors:assign',
    'admin:challenge_sponsors:create',
    'admin:challenge_sponsors:read',
    'admin:challenge_sponsors:update',
    'admin:challenge_sponsors:delete',
    'admin:challenge_requirements:create',
    'admin:challenge_requirements:read',
    'admin:challenge_requirements:update',
    'admin:challenge_requirements:delete',
    'admin:challenge_objectives:create',
    'admin:challenge_objectives:read',
    'admin:challenge_objectives:update',
    'admin:challenge_objectives:delete',
    'admin:challenge_risks:create',
    'admin:challenge_risks:read',
    'admin:challenge_risks:update',
    'admin:challenge_risks:delete',
    'admin:challenge_timelines:create',
    'admin:challenge_timelines:read',
    'admin:challenge_timelines:update',
    'admin:challenge_timelines:delete',
    'admin:ideas:create',
    'admin:ideas:read',
    'admin:ideas:update',
    'admin:ideas:delete',
    'admin:ideas:forceDelete',
    'admin:ideas:restore',
    'admin:ideas:approve',
    'admin:ideas:reject',
    'admin:ideas:evaluate',
    'admin:idea_steps:create',
    'admin:idea_steps:read',
    'admin:idea_steps:update',
    'admin:idea_steps:delete',
    'admin:idea_team_members:create',
    'admin:idea_team_members:read',
    'admin:idea_team_members:update',
    'admin:idea_team_members:delete',
    'admin:idea_evaluators:create',
    'admin:idea_evaluators:read',
    'admin:idea_evaluators:update',
    'admin:idea_evaluators:delete',
    'admin:idea_evaluators:assign',
    'admin:idea_methodologies:create',
    'admin:idea_methodologies:read',
    'admin:idea_methodologies:update',
    'admin:idea_methodologies:delete',
    'admin:innovation_types:create',
    'admin:innovation_types:read',
    'admin:innovation_types:update',
    'admin:innovation_types:delete',
    'admin:innovation_methodologies:create',
    'admin:innovation_methodologies:read',
    'admin:innovation_methodologies:update',
    'admin:innovation_methodologies:delete',
    'admin:evaluation_templates:create',
    'admin:evaluation_templates:read',
    'admin:evaluation_templates:update',
    'admin:evaluation_templates:delete',
    'admin:evaluation_stages:create',
    'admin:evaluation_stages:read',
    'admin:evaluation_stages:update',
    'admin:evaluation_stages:delete',
    'admin:evaluation_factors:create',
    'admin:evaluation_factors:read',
    'admin:evaluation_factors:update',
    'admin:evaluation_factors:delete',
    'admin:evaluation_factor_items:create',
    'admin:evaluation_factor_items:read',
    'admin:evaluation_factor_items:update',
    'admin:evaluation_factor_items:delete',
    'admin:evaluation_factor_specialties:create',
    'admin:evaluation_factor_specialties:read',
    'admin:evaluation_factor_specialties:update',
    'admin:evaluation_factor_specialties:delete',
    'admin:evaluation_factor_specialties:assign',
    'admin:evaluation_factor_stages:create',
    'admin:evaluation_factor_stages:read',
    'admin:evaluation_factor_stages:update',
    'admin:evaluation_factor_stages:delete',
    'admin:evaluation_assessment_values:create',
    'admin:evaluation_assessment_values:read',
    'admin:evaluation_assessment_values:update',
    'admin:evaluation_assessment_values:delete',
    'admin:evaluation_assessment_recommendations:create',
    'admin:evaluation_assessment_recommendations:read',
    'admin:evaluation_assessment_recommendations:update',
    'admin:evaluation_assessment_recommendations:delete',
    'admin:jury_members:create',
    'admin:jury_members:read',
    'admin:jury_members:update',
    'admin:jury_members:delete',
    'admin:jury_members:assign',
    'admin:comments:create',
    'admin:comments:read',
    'admin:comments:update',
    'admin:comments:delete',
    'admin:comments:moderate',
    'admin:likes:create',
    'admin:likes:read',
    'admin:likes:delete',
    'admin:bookmarks:create',
    'admin:bookmarks:read',
    'admin:bookmarks:delete',
    'admin:attachments:create',
    'admin:attachments:read',
    'admin:attachments:update',
    'admin:attachments:delete',
    'admin:attachments:download',
    'admin:issue_reports:create',
    'admin:issue_reports:read',
    'admin:issue_reports:update',
    'admin:issue_reports:delete',
    'admin:issue_reports:resolve',
    'admin:user_profiles:read',
    'admin:user_profiles:update',
    'admin:user_profiles:delete',
    'admin:user_specialties:read',
    'admin:user_specialties:update',
    'admin:user_specialties:assign',
    'admin:user_specialties:revoke',
    'admin:settings:read',
    'admin:settings:update',
    'admin:audit_logs:read',
    'admin:audit_logs:export',
    'admin:notifications:create',
    'admin:notifications:read',
    'admin:notifications:update',
    'admin:notifications:delete',
    'admin:notifications:send',
    'admin:translations:read',
    'admin:translations:update',
    'admin:backups:create',
    'admin:backups:read',
    'admin:backups:download',
    'admin:backups:restore',
    'admin:cache:clear',
    'admin:maintenance:enable',
    'admin:maintenance:disable',
    'admin:panel_access',
    'admin:view_statistics',
    'admin:export_data',
    'admin:import_data',
    'admin:bulk_actions',
    'admin:impersonate_users',
    'admin:manage_settings',
    'admin:view_system_info',
    'admin:manage_integrations',
    'user:challenges:read',
    'user:challenges:participate',
    'user:challenges:submit',
    'user:ideas:create',
    'user:ideas:read',
    'user:ideas:update',
    'user:ideas:delete',
    'user:ideas:submit',
    'user:comments:create',
    'user:comments:read',
    'user:comments:update',
    'user:comments:delete',
    'user:likes:create',
    'user:likes:delete',
    'user:bookmarks:create',
    'user:bookmarks:read',
    'user:bookmarks:delete',
    'user:attachments:create',
    'user:attachments:read',
    'user:attachments:delete',
    'user:attachments:download',
    'user:issue_reports:create',
    'user:issue_reports:read',
    'user:user_profiles:read',
    'user:user_profiles:update',
    'user:view_own_submissions',
    'user:edit_own_submissions',
    'user:delete_own_submissions',
    'user:view_public_content',
    'user:participate_in_challenges',
    'user:submit_ideas',
    'user:vote',
    'user:comment',
    'user:upload_files',
    'evaluator:ideas:read',
    'evaluator:ideas:evaluate',
    'evaluator:evaluation_assessment_values:create',
    'evaluator:evaluation_assessment_values:read',
    'evaluator:evaluation_assessment_values:update',
    'evaluator:evaluation_assessment_recommendations:create',
    'evaluator:evaluation_assessment_recommendations:read',
    'evaluator:evaluation_assessment_recommendations:update',
    'evaluator:comments:create',
    'evaluator:comments:read',
    'evaluator:evaluate_ideas',
    'evaluator:submit_assessments',
    'evaluator:view_assigned_ideas',
    'evaluator:provide_recommendations',
    'jury:ideas:read',
    'jury:ideas:evaluate',
    'jury:ideas:score',
    'jury:challenges:read',
    'jury:evaluation_stages:read',
    'jury:final_evaluation',
    'jury:select_winners',
    'jury:view_all_submissions',
    'jury:access_jury_panel',
    'mentor:challenges:read',
    'mentor:challenges:mentor',
    'mentor:ideas:read',
    'mentor:ideas:guide',
    'mentor:comments:create',
    'mentor:comments:read',
    'mentor:mentor_participants',
    'mentor:provide_guidance',
    'mentor:view_assigned_challenges',
] as const;

export const allUserTypes: readonly UserType[] = [
    'admin',
    'evaluator',
    'jury',
    'mentor',
    'super-admin',
    'user',
] as const;

