/**
 * Auto-generated route helpers — do not edit.
 * Generated by Innovation.TsGen
 */

export interface RouteDefinition<M extends string = string> {
    url: string;
    method: M;
}

/** @controller Auth @action BackchannelLogout @route '/auth/backchannel-logout' @method post */
export const backchannellogout = (): RouteDefinition<'post'> => ({
    url: '/auth/backchannel-logout',
    method: 'post',
})

backchannellogout.url = () => '/auth/backchannel-logout'

