/**
 * Auto-generated permission utilities — do not edit.
 * Generated by Innovation.TsGen
 */
import { type ReactNode } from 'react';
import { usePage } from '@inertiajs/react';
import type { SharedData } from '@/types';
import type { Permission, UserType } from '@/types/permissions';

export interface UserPermissions {
    roles: string[];
    permissions: string[];
    hasPermission: (permission: Permission | Permission[]) => boolean;
    hasAnyPermission: (permissions: Permission[]) => boolean;
    hasAllPermissions: (permissions: Permission[]) => boolean;
    hasRole: (role: UserType | string) => boolean;
    hasAnyRole: (roles: string[]) => boolean;
    hasAllRoles: (roles: string[]) => boolean;
}

export function usePermissions(): UserPermissions {
    const { auth } = usePage<SharedData>().props;
    const userPermissions = (auth.permissions || []) as string[];
    const userRoles = (auth.roles || []) as string[];

    const hasPermission = (permission: Permission | Permission[]): boolean => {
        if (Array.isArray(permission)) {
            return permission.some((p) => userPermissions.includes(p));
        }
        return userPermissions.includes(permission);
    };

    const hasAnyPermission = (permissions: Permission[]): boolean =>
        permissions.some((p) => userPermissions.includes(p));

    const hasAllPermissions = (permissions: Permission[]): boolean =>
        permissions.every((p) => userPermissions.includes(p));

    const hasRole = (role: UserType | string): boolean =>
        userRoles.includes(role);

    const hasAnyRole = (roles: string[]): boolean =>
        roles.some((r) => userRoles.includes(r));

    const hasAllRoles = (roles: string[]): boolean =>
        roles.every((r) => userRoles.includes(r));

    return {
        roles: userRoles,
        permissions: userPermissions,
        hasPermission,
        hasAnyPermission,
        hasAllPermissions,
        hasRole,
        hasAnyRole,
        hasAllRoles,
    };
}

interface CanProps {
    permission?: Permission;
    permissions?: Permission[];
    role?: UserType | string;
    roles?: string[];
    requireAll?: boolean;
    fallback?: ReactNode;
    children: ReactNode;
}

export function Can({
    permission,
    permissions,
    role,
    roles,
    requireAll = false,
    fallback = null,
    children,
}: CanProps): ReactNode {
    const { hasPermission, hasAnyPermission, hasAllPermissions, hasRole, hasAnyRole, hasAllRoles } =
        usePermissions();

    let authorized = false;

    if (permission) {
        authorized = hasPermission(permission);
    } else if (permissions && permissions.length > 0) {
        authorized = requireAll ? hasAllPermissions(permissions) : hasAnyPermission(permissions);
    } else if (role) {
        authorized = hasRole(role);
    } else if (roles && roles.length > 0) {
        authorized = requireAll ? hasAllRoles(roles) : hasAnyRole(roles);
    }

    return authorized ? children : fallback;
}