/**
 * Auto-generated route helpers — do not edit.
 * Generated by Innovation.TsGen
 */

export interface RouteDefinition<M extends string = string> {
    url: string;
    method: M;
}

/** @controller Home @action Index @route '/' */
export const index = (): RouteDefinition<'get'> => ({
    url: '/',
    method: 'get',
})

index.url = () => '/'

/** @controller Auth @action Dashboard @route '/dashboard' */
export const dashboard = (): RouteDefinition<'get'> => ({
    url: '/dashboard',
    method: 'get',
})

dashboard.url = () => '/dashboard'

/** @controller Auth @action Login @route '/login' */
export const login = (): RouteDefinition<'get'> => ({
    url: '/login',
    method: 'get',
})

login.url = () => '/login'

/** @controller Auth @action Register @route '/register' */
export const register = (): RouteDefinition<'get'> => ({
    url: '/register',
    method: 'get',
})

register.url = () => '/register'

// Sub-routes
export * as api from './api'

