/**
 * Auto-generated route helpers — do not edit.
 * Generated by Innovation.TsGen
 */

export interface RouteDefinition<M extends string = string> {
    url: string;
    method: M;
}

/** @controller Home @action Home @route '/' */
export const home = (): RouteDefinition<'get'> => ({
    url: '/',
    method: 'get',
})

home.url = () => '/'

/** @controller Auth @action Dashboard @route '/dashboard' */
export const dashboard = (): RouteDefinition<'get'> => ({
    url: '/dashboard',
    method: 'get',
})

dashboard.url = () => '/dashboard'

/** @controller Auth @action Login @route '/login' */
export const login = (): RouteDefinition<'get'> => ({
    url: '/login',
    method: 'get',
})

login.url = () => '/login'

/** @controller Auth @action LoginPost @route '/login' */
export const loginPost = (): RouteDefinition<'post'> => ({
    url: '/login',
    method: 'post',
})

loginPost.url = () => '/login'

/** @controller Auth @action Logout @route '/logout' */
export const logout = (): RouteDefinition<'post'> => ({
    url: '/logout',
    method: 'post',
})

logout.url = () => '/logout'

/** @controller Auth @action Register @route '/register' */
export const register = (): RouteDefinition<'get'> => ({
    url: '/register',
    method: 'get',
})

register.url = () => '/register'

/** @controller Auth @action RegisterPost @route '/register' */
export const registerPost = (): RouteDefinition<'post'> => ({
    url: '/register',
    method: 'post',
})

registerPost.url = () => '/register'



