/**
 * Auto-generated route helpers — do not edit.
 * Generated by Innovation.TsGen
 */

export interface RouteDefinition<M extends string = string> {
    url: string;
    method: M;
}

/** @controller Home @action Home @route '/' @method get */
export const home = (): RouteDefinition<'get'> => ({
    url: '/',
    method: 'get',
})

home.url = () => '/'

/** @controller Antiforgery @action token @route '/antiforgery/token' @method get */
export const token = (): RouteDefinition<'get'> => ({
    url: '/antiforgery/token',
    method: 'get',
})

token.url = () => '/antiforgery/token'

/** @controller Auth @action Dashboard @route '/dashboard' @method get */
export const dashboard = (): RouteDefinition<'get'> => ({
    url: '/dashboard',
    method: 'get',
})

dashboard.url = () => '/dashboard'

/** @controller Auth @action Login @route '/login' @method get */
export const login = (): RouteDefinition<'get'> => ({
    url: '/login',
    method: 'get',
})

login.url = () => '/login'

/** @controller Auth @action Logout @route '/logout' @method post */
export const logout = (): RouteDefinition<'post'> => ({
    url: '/logout',
    method: 'post',
})

logout.url = () => '/logout'

/** @controller Auth @action Register @route '/register' @method get */
export const register = (): RouteDefinition<'get'> => ({
    url: '/register',
    method: 'get',
})

register.url = () => '/register'

// Sub-routes
export * as admin from './admin'
export * as auth from './auth'

