/**
 * Auto-generated route helpers — do not edit.
 * Generated by Innovation.TsGen
 */

export interface RouteDefinition<M extends string = string> {
    url: string;
    method: M;
}

/** @controller Auth @action me @route '/user/me' @method get */
export const me = (): RouteDefinition<'get'> => ({
    url: '/user/me',
    method: 'get',
})

me.url = () => '/user/me'

