/**
 * Auto-generated route helpers — do not edit.
 * Generated by Innovation.TsGen
 */

export interface RouteDefinition<M extends string = string> {
    url: string;
    method: M;
}

/** @controller Challenge @action Index @route '/admin/challenges/' @method get */
export const index = (): RouteDefinition<'get'> => ({
    url: '/admin/challenges/',
    method: 'get',
})

index.url = () => '/admin/challenges/'

/** @controller Challenge @action Show @route '/admin/challenges/{id}' @method get */
export const show = (args: { id: string | number }): RouteDefinition<'get'> => ({
    url: `/admin/challenges/${args.id}`,
    method: 'get',
})

show.url = (args: { id: string | number }) => `/admin/challenges/${args.id}`

/** @controller Challenge @action Edit @route '/admin/challenges/{id}/edit' @method get */
export const edit = (args: { id: string | number }): RouteDefinition<'get'> => ({
    url: `/admin/challenges/${args.id}/edit`,
    method: 'get',
})

edit.url = (args: { id: string | number }) => `/admin/challenges/${args.id}/edit`

/** @controller Challenge @action Create @route '/admin/challenges/create' @method get */
export const create = (): RouteDefinition<'get'> => ({
    url: '/admin/challenges/create',
    method: 'get',
})

create.url = () => '/admin/challenges/create'

