/**
 * Auto-generated route helpers — do not edit.
 * Generated by Innovation.TsGen
 */

export interface RouteDefinition<M extends string = string> {
    url: string;
    method: M;
}

/** @controller Challenge @action Index @route '/admin/challenges/' @method get */
export const index = (): RouteDefinition<'get'> => ({
    url: '/admin/challenges/',
    method: 'get',
})

index.url = () => '/admin/challenges/'

/** @controller Challenge @action Store @route '/admin/challenges/' @method post */
export const store = (): RouteDefinition<'post'> => ({
    url: '/admin/challenges/',
    method: 'post',
})

store.url = () => '/admin/challenges/'

/** @controller Challenge @action Show @route '/admin/challenges/{id}' @method get */
export const show = (args: { id: string | number }): RouteDefinition<'get'> => ({
    url: `/admin/challenges/${args.id}`,
    method: 'get',
})

show.url = (args: { id: string | number }) => `/admin/challenges/${args.id}`

/** @controller Challenge @action Update @route '/admin/challenges/{id}' @method put */
export const update = (args: { id: string | number }): RouteDefinition<'put'> => ({
    url: `/admin/challenges/${args.id}`,
    method: 'put',
})

update.url = (args: { id: string | number }) => `/admin/challenges/${args.id}`

/** @controller Challenge @action Destroy @route '/admin/challenges/{id}' @method delete */
export const destroy = (args: { id: string | number }): RouteDefinition<'delete'> => ({
    url: `/admin/challenges/${args.id}`,
    method: 'delete',
})

destroy.url = (args: { id: string | number }) => `/admin/challenges/${args.id}`

/** @controller Challenge @action Advance @route '/admin/challenges/{id}/advance' @method post */
export const advance = (args: { id: string | number }): RouteDefinition<'post'> => ({
    url: `/admin/challenges/${args.id}/advance`,
    method: 'post',
})

advance.url = (args: { id: string | number }) => `/admin/challenges/${args.id}/advance`

/** @controller Challenge @action Edit @route '/admin/challenges/{id}/edit' @method get */
export const edit = (args: { id: string | number }): RouteDefinition<'get'> => ({
    url: `/admin/challenges/${args.id}/edit`,
    method: 'get',
})

edit.url = (args: { id: string | number }) => `/admin/challenges/${args.id}/edit`

/** @controller Challenge @action Create @route '/admin/challenges/create' @method get */
export const create = (): RouteDefinition<'get'> => ({
    url: '/admin/challenges/create',
    method: 'get',
})

create.url = () => '/admin/challenges/create'

