/**
 * Auto-generated route helpers — do not edit.
 * Generated by Innovation.TsGen
 */

export interface RouteDefinition<M extends string = string> {
    url: string;
    method: M;
}

/** @controller Challenge @action Index @route '/admin/challenges/' */
export const index = (): RouteDefinition<'get'> => ({
    url: '/admin/challenges/',
    method: 'get',
})

index.url = () => '/admin/challenges/'

/** @controller Challenge @action Show @route '/admin/challenges/{id}' */
export const show = (args: { id: string | number }): RouteDefinition<'get'> => ({
    url: `/admin/challenges/${args.id}`,
    method: 'get',
})

show.url = (args: { id: string | number }) => `/admin/challenges/${args.id}`

// Sub-routes
export * as challenges from './challenges'

