/**
 * Auto-generated route helpers — do not edit.
 * Generated by Innovation.TsGen
 */

export interface RouteDefinition<M extends string = string> {
    url: string;
    method: M;
}

// Sub-routes
export * as challenges from './challenges'
export * as roles from './roles'

