/**
 * Auto-generated route helpers — do not edit.
 * Generated by Innovation.TsGen
 */

export interface RouteDefinition<M extends string = string> {
    url: string;
    method: M;
}

/** @controller Role @action Index @route '/admin/roles/' @method get */
export const index = (): RouteDefinition<'get'> => ({
    url: '/admin/roles/',
    method: 'get',
})

index.url = () => '/admin/roles/'

/** @controller Role @action Store @route '/admin/roles/' @method post */
export const store = (): RouteDefinition<'post'> => ({
    url: '/admin/roles/',
    method: 'post',
})

store.url = () => '/admin/roles/'

/** @controller Role @action Show @route '/admin/roles/{id}' @method get */
export const show = (args: { id: string | number }): RouteDefinition<'get'> => ({
    url: `/admin/roles/${args.id}`,
    method: 'get',
})

show.url = (args: { id: string | number }) => `/admin/roles/${args.id}`

/** @controller Role @action Update @route '/admin/roles/{id}' @method put */
export const update = (args: { id: string | number }): RouteDefinition<'put'> => ({
    url: `/admin/roles/${args.id}`,
    method: 'put',
})

update.url = (args: { id: string | number }) => `/admin/roles/${args.id}`

/** @controller Role @action Destroy @route '/admin/roles/{id}' @method delete */
export const destroy = (args: { id: string | number }): RouteDefinition<'delete'> => ({
    url: `/admin/roles/${args.id}`,
    method: 'delete',
})

destroy.url = (args: { id: string | number }) => `/admin/roles/${args.id}`

/** @controller Role @action Edit @route '/admin/roles/{id}/edit' @method get */
export const edit = (args: { id: string | number }): RouteDefinition<'get'> => ({
    url: `/admin/roles/${args.id}/edit`,
    method: 'get',
})

edit.url = (args: { id: string | number }) => `/admin/roles/${args.id}/edit`

/** @controller Role @action Create @route '/admin/roles/create' @method get */
export const create = (): RouteDefinition<'get'> => ({
    url: '/admin/roles/create',
    method: 'get',
})

create.url = () => '/admin/roles/create'

