using System.Collections;
using System.Text;
using Innovation.Application.Common.Models;
using Innovation.TsGen.Helpers;

namespace Innovation.TsGen.Generators;

public static class FilterGenerator
{
    public static void Generate()
    {
        var root = RouteHelpers.FindProjectRoot();
        var outputPath = Path.Combine(
            root,
            "src",
            "Innovation.Web",
            "ClientApp",
            "src",
            "types",
            "filters.ts"
        );

        Console.WriteLine("[4/4] Generating filter definitions...");

        var appAssembly = typeof(FilteredQuery<>).Assembly;
        var filterDefs =
            new List<(
                string Name,
                string EntityName,
                List<string> Fields,
                string DefaultOrderBy
            )>();

        foreach (var type in appAssembly.GetTypes())
        {
            if (type.IsAbstract || type.IsInterface)
                continue;

            var baseType = type.BaseType;
            if (baseType is null || !baseType.IsGenericType)
                continue;
            if (baseType.GetGenericTypeDefinition() != typeof(FilteredQuery<>))
                continue;

            var entityName = baseType.GetGenericArguments()[0].Name;
            var instance = Activator.CreateInstance(type);
            if (instance is null)
                continue;

            var mapperProp = baseType.GetProperty("Mapper");
            var defaultOrderByProp = baseType.GetProperty("DefaultOrderBy");
            var mapper = mapperProp?.GetValue(instance);
            var defaultOrderBy =
                defaultOrderByProp?.GetValue(instance) as string ?? "createdAt desc";

            var fields = new List<string>();

            var getCurrentMaps = mapper?.GetType().GetMethod("GetCurrentMaps");
            if (getCurrentMaps != null)
            {
                var maps = getCurrentMaps.Invoke(mapper, null) as IEnumerable;
                if (maps != null)
                {
                    foreach (var map in maps)
                    {
                        var fromProp = map.GetType().GetProperty("From");
                        var fieldName = fromProp?.GetValue(map) as string;
                        if (fieldName != null)
                            fields.Add(fieldName);
                    }
                }
            }

            var name = type.Name.Replace("FilteredQuery", "");
            filterDefs.Add((name, entityName, fields, defaultOrderBy));
            Console.WriteLine($"  {name}: {fields.Count} fields");
        }

        var content = GenerateTs(filterDefs);
        Directory.CreateDirectory(Path.GetDirectoryName(outputPath)!);
        File.WriteAllText(outputPath, content);
        Console.WriteLine($"  → {outputPath}");
    }

    private static string GenerateTs(
        List<(string Name, string EntityName, List<string> Fields, string DefaultOrderBy)> defs
    )
    {
        var sb = new StringBuilder();

        sb.AppendLine("/**");
        sb.AppendLine(" * Auto-generated filter/sort definitions — do not edit.");
        sb.AppendLine(" * Generated by Innovation.TsGen");
        sb.AppendLine(" */");
        sb.AppendLine();

        // GridifyQuery interface
        sb.AppendLine("export interface GridifyQuery {");
        sb.AppendLine("  page?: number;");
        sb.AppendLine("  pageSize?: number;");
        sb.AppendLine("  orderBy?: string | null;");
        sb.AppendLine("  filter?: string | null;");
        sb.AppendLine("}");
        sb.AppendLine();

        // Gridify filter operators
        sb.AppendLine(
            "export type FilterOperator = '=' | '!=' | '<' | '>' | '<=' | '>=' | '=*' | '!*' | '^' | '!^' | '$' | '!$';"
        );
        sb.AppendLine();

        // Per-entity definitions
        foreach (var (name, entityName, fields, defaultOrderBy) in defs)
        {
            var camelName = RouteHelpers.ToCamelCase(name);
            var pascalName = name;

            sb.AppendLine($"// {pascalName} filterable/sortable fields");
            sb.AppendLine($"export const {camelName}Fields = [");
            foreach (var field in fields)
            {
                sb.AppendLine($"  '{field}',");
            }
            sb.AppendLine("] as const;");
            sb.AppendLine();

            sb.AppendLine($"export type {pascalName}Field = typeof {camelName}Fields[number];");
            sb.AppendLine();

            sb.AppendLine(
                $"export type {pascalName}OrderBy = `${{{pascalName}Field}} asc` | `${{{pascalName}Field}} desc`;"
            );
            sb.AppendLine();

            sb.AppendLine($"export const {camelName}DefaultOrderBy = '{defaultOrderBy}';");
            sb.AppendLine();
        }

        // Helper functions
        sb.AppendLine("// Filter builder helpers");
        sb.AppendLine(
            "export function filter<F extends string>(field: F, op: FilterOperator, value: string | number | boolean): string {"
        );
        sb.AppendLine("  return `${field}${op}${value}`;");
        sb.AppendLine("}");
        sb.AppendLine();

        sb.AppendLine("export function and(...filters: string[]): string {");
        sb.AppendLine("  return filters.join(',');");
        sb.AppendLine("}");
        sb.AppendLine();

        sb.AppendLine("export function or(...filters: string[]): string {");
        sb.AppendLine("  return filters.join('|');");
        sb.AppendLine("}");
        sb.AppendLine();


        // Sort option helpers
        sb.AppendLine("// Sort option helpers");
        sb.AppendLine("export type SortDirection = 'asc' | 'desc';");
        sb.AppendLine();
        sb.AppendLine("export interface SortValue<F extends string = string> {");
        sb.AppendLine("  field: F;");
        sb.AppendLine("  direction: SortDirection;");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("export function sortOption<F extends string>(");
        sb.AppendLine("  field: F,");
        sb.AppendLine("  direction: SortDirection,");
        sb.AppendLine("  label: string,");
        sb.AppendLine("): { value: string; label: string; sort: SortValue<F> } {");
        sb.AppendLine("  return { value: `${field} ${direction}`, label, sort: { field, direction } };");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("export function parseSortValue<F extends string>(value: string): SortValue<F> {");
        sb.AppendLine("  const idx = value.lastIndexOf(' ');");
        sb.AppendLine("  if (idx === -1) return { field: value as F, direction: 'desc' };");
        sb.AppendLine("  return { field: value.substring(0, idx) as F, direction: value.substring(idx + 1) as SortDirection };");
        sb.AppendLine("}");
        sb.AppendLine();

        return sb.ToString();
    }
}
