using System.Text;
using Innovation.Infrastructure.Data.Seeders;
using Innovation.TsGen.Helpers;

namespace Innovation.TsGen.Generators;

public static class PermissionGenerator
{
    public static void Generate()
    {
        var root = RouteHelpers.FindProjectRoot();
        var clientAppSrc = Path.Combine(root, "src", "Innovation.Web", "ClientApp", "src");

        Console.WriteLine("[3/3] Generating permissions...");

        var allPermissions = PermissionSeederConfig.GenerateAllPermissions();
        var allRoles = PermissionSeederConfig.DefaultRoles.Keys.OrderBy(r => r).ToList();

        // 1. Generate types/permissions.ts
        var typesDir = Path.Combine(clientAppSrc, "types");
        Directory.CreateDirectory(typesDir);
        var typesFile = Path.Combine(typesDir, "permissions.ts");
        File.WriteAllText(typesFile, GeneratePermissionTypes(allPermissions, allRoles));
        Console.WriteLine(
            $"  → {Path.GetRelativePath(root, typesFile)} ({allPermissions.Count} permissions)"
        );

        // 2. Generate hooks/use-permissions.tsx
        var hooksDir = Path.Combine(clientAppSrc, "hooks");
        Directory.CreateDirectory(hooksDir);
        var hookFile = Path.Combine(hooksDir, "use-permissions.tsx");
        File.WriteAllText(hookFile, GeneratePermissionHook());
        Console.WriteLine($"  → {Path.GetRelativePath(root, hookFile)}");
    }

    private static string GeneratePermissionTypes(List<string> permissions, List<string> roles)
    {
        var sb = new StringBuilder();

        sb.AppendLine("/**");
        sb.AppendLine(" * Auto-generated permission types — do not edit.");
        sb.AppendLine(" * Generated by Innovation.TsGen");
        sb.AppendLine(" */");
        sb.AppendLine();

        // Permission union type
        sb.AppendLine("export type Permission =");
        for (int i = 0; i < permissions.Count; i++)
        {
            var separator = i == permissions.Count - 1 ? ";" : "";
            sb.AppendLine($"    | '{permissions[i]}'{separator}");
        }
        sb.AppendLine();

        // UserType union type
        sb.AppendLine("export type UserType =");
        for (int i = 0; i < roles.Count; i++)
        {
            var separator = i == roles.Count - 1 ? ";" : "";
            sb.AppendLine($"    | '{roles[i]}'{separator}");
        }
        sb.AppendLine();

        // Permission groups for UI (grouped by prefix)
        var grouped = permissions
            .GroupBy(p => p.Contains(':') ? p[..p.IndexOf(':')] : "other")
            .OrderBy(g => g.Key);

        sb.AppendLine("export const permissionGroups: Record<string, readonly Permission[]> = {");
        foreach (var group in grouped)
        {
            sb.AppendLine($"    '{group.Key}': [");
            foreach (var perm in group.OrderBy(p => p))
            {
                sb.AppendLine($"        '{perm}',");
            }
            sb.AppendLine("    ],");
        }
        sb.AppendLine("} as const;");
        sb.AppendLine();

        sb.AppendLine("export const allPermissions: readonly Permission[] = [");
        foreach (var perm in permissions)
        {
            sb.AppendLine($"    '{perm}',");
        }
        sb.AppendLine("] as const;");
        sb.AppendLine();

        sb.AppendLine("export const allUserTypes: readonly UserType[] = [");
        foreach (var role in roles)
        {
            sb.AppendLine($"    '{role}',");
        }
        sb.AppendLine("] as const;");
        sb.AppendLine();

        return sb.ToString();
    }

    private static string GeneratePermissionHook()
    {
        return """
            /**
             * Auto-generated permission utilities — do not edit.
             * Generated by Innovation.TsGen
             */
            import { type ReactNode } from 'react';
            import { usePage } from '@inertiajs/react';
            import type { SharedData } from '@/types';
            import type { Permission, UserType } from '@/types/permissions';

            export interface UserPermissions {
                roles: string[];
                permissions: string[];
                hasPermission: (permission: Permission | Permission[]) => boolean;
                hasAnyPermission: (permissions: Permission[]) => boolean;
                hasAllPermissions: (permissions: Permission[]) => boolean;
                hasRole: (role: UserType | string) => boolean;
                hasAnyRole: (roles: string[]) => boolean;
                hasAllRoles: (roles: string[]) => boolean;
            }

            export function usePermissions(): UserPermissions {
                const { auth } = usePage<SharedData>().props;
                const userPermissions = (auth.permissions || []) as string[];
                const userRoles = (auth.roles || []) as string[];

                const hasPermission = (permission: Permission | Permission[]): boolean => {
                    if (Array.isArray(permission)) {
                        return permission.some((p) => userPermissions.includes(p));
                    }
                    return userPermissions.includes(permission);
                };

                const hasAnyPermission = (permissions: Permission[]): boolean =>
                    permissions.some((p) => userPermissions.includes(p));

                const hasAllPermissions = (permissions: Permission[]): boolean =>
                    permissions.every((p) => userPermissions.includes(p));

                const hasRole = (role: UserType | string): boolean =>
                    userRoles.includes(role);

                const hasAnyRole = (roles: string[]): boolean =>
                    roles.some((r) => userRoles.includes(r));

                const hasAllRoles = (roles: string[]): boolean =>
                    roles.every((r) => userRoles.includes(r));

                return {
                    roles: userRoles,
                    permissions: userPermissions,
                    hasPermission,
                    hasAnyPermission,
                    hasAllPermissions,
                    hasRole,
                    hasAnyRole,
                    hasAllRoles,
                };
            }

            interface CanProps {
                permission?: Permission;
                permissions?: Permission[];
                role?: UserType | string;
                roles?: string[];
                requireAll?: boolean;
                fallback?: ReactNode;
                children: ReactNode;
            }

            export function Can({
                permission,
                permissions,
                role,
                roles,
                requireAll = false,
                fallback = null,
                children,
            }: CanProps): ReactNode {
                const { hasPermission, hasAnyPermission, hasAllPermissions, hasRole, hasAnyRole, hasAllRoles } =
                    usePermissions();

                let authorized = false;

                if (permission) {
                    authorized = hasPermission(permission);
                } else if (permissions && permissions.length > 0) {
                    authorized = requireAll ? hasAllPermissions(permissions) : hasAnyPermission(permissions);
                } else if (role) {
                    authorized = hasRole(role);
                } else if (roles && roles.length > 0) {
                    authorized = requireAll ? hasAllRoles(roles) : hasAnyRole(roles);
                }

                return authorized ? children : fallback;
            }
            """;
    }
}
