using System.Text;
using Innovation.TsGen.Discovery;
using Innovation.TsGen.Helpers;
using Innovation.TsGen.Models;

namespace Innovation.TsGen.Generators;

public static class RouteGenerator
{
    public static void Generate()
    {
        var root = RouteHelpers.FindProjectRoot();
        var clientAppSrc = Path.Combine(root, "src", "Innovation.Web", "ClientApp", "src");
        var routesDir = Path.Combine(clientAppSrc, "routes");
        var endpointsDir = Path.Combine(root, "src", "Innovation.Web", "Endpoints");

        Console.WriteLine("[2/3] Generating routes...");
        var controllerRoutes = ControllerRouteDiscovery.Discover();
        Console.WriteLine($"  Controllers: {controllerRoutes.Count} routes");

        var endpointRoutes = EndpointRouteDiscovery.Discover(endpointsDir);
        Console.WriteLine($"  Endpoints:   {endpointRoutes.Count} routes");

        var allRoutes = controllerRoutes.Concat(endpointRoutes).OrderBy(r => r.Url).ToList();
        var fileCount = GenerateRouteFiles(routesDir, allRoutes);
        Console.WriteLine($"  → {allRoutes.Count} total routes in {fileCount} files");
    }

    private static int GenerateRouteFiles(string routesDir, List<RouteInfo> routes)
    {
        if (Directory.Exists(routesDir))
            Directory.Delete(routesDir, recursive: true);

        Directory.CreateDirectory(routesDir);

        var dirGroups = new Dictionary<string, List<RouteInfo>>();

        foreach (var route in routes)
        {
            var dirPath = GetRouteDirectory(route);
            if (!dirGroups.ContainsKey(dirPath))
                dirGroups[dirPath] = [];
            dirGroups[dirPath].Add(route);
        }

        if (!dirGroups.ContainsKey(""))
            dirGroups[""] = [];

        var allDirs = dirGroups.Keys.ToHashSet();
        var intermediates = new HashSet<string>();
        foreach (var dir in allDirs)
        {
            var parts = dir.Split('/', StringSplitOptions.RemoveEmptyEntries);
            for (int i = 1; i < parts.Length; i++)
            {
                var intermediate = string.Join("/", parts.Take(i));
                if (!allDirs.Contains(intermediate))
                    intermediates.Add(intermediate);
            }
        }
        foreach (var intermediate in intermediates)
            dirGroups[intermediate] = [];

        int fileCount = 0;

        foreach (var (dirPath, dirRoutes) in dirGroups.OrderBy(g => g.Key))
        {
            var fullDir = string.IsNullOrEmpty(dirPath)
                ? routesDir
                : Path.Combine(
                    routesDir,
                    dirPath.Replace("/", Path.DirectorySeparatorChar.ToString())
                );

            Directory.CreateDirectory(fullDir);

            var content = GenerateDirectoryIndexTs(dirPath, dirRoutes, dirGroups);
            File.WriteAllText(Path.Combine(fullDir, "index.ts"), content);
            fileCount++;
        }

        var allGeneratedDirs = Directory
            .GetDirectories(routesDir, "*", SearchOption.AllDirectories)
            .OrderByDescending(d => d.Length)
            .ToList();

        foreach (var dir in allGeneratedDirs)
        {
            var subDirs = Directory.GetDirectories(dir);
            var files = Directory.GetFiles(dir);

            if (
                subDirs.Length == 0
                && files.Length == 1
                && Path.GetFileName(files[0]) == "index.ts"
            )
            {
                var dirName = new DirectoryInfo(dir).Name;
                var parentDir = Directory.GetParent(dir)!.FullName;
                var targetFile = Path.Combine(parentDir, $"{dirName}.ts");

                File.Move(files[0], targetFile);
                Directory.Delete(dir);
                fileCount--;
            }
        }

        return fileCount;
    }

    private static string GetRouteDirectory(RouteInfo route)
    {
        var segments = route
            .Url.Trim('/')
            .Split('/', StringSplitOptions.RemoveEmptyEntries)
            .Where(s => !s.StartsWith('{'))
            .ToList();

        if (segments.Count <= 1)
            return "";

        if (segments.Last().Equals(route.Action, StringComparison.OrdinalIgnoreCase))
            segments.RemoveAt(segments.Count - 1);

        if (segments.Count <= 1)
            return "";

        return string.Join("/", segments);
    }

    private static string GenerateDirectoryIndexTs(
        string dirPath,
        List<RouteInfo> routes,
        Dictionary<string, List<RouteInfo>> allGroups
    )
    {
        var sb = new StringBuilder();

        sb.AppendLine("/**");
        sb.AppendLine(" * Auto-generated route helpers — do not edit.");
        sb.AppendLine(" * Generated by Innovation.TsGen");
        sb.AppendLine(" */");
        sb.AppendLine();

        var childDirs = allGroups
            .Keys.Where(k => k != dirPath && IsDirectChild(dirPath, k))
            .OrderBy(k => k)
            .ToList();

        sb.AppendLine("export interface RouteDefinition<M extends string = string> {");
        sb.AppendLine("    url: string;");
        sb.AppendLine("    method: M;");
        sb.AppendLine("}");
        sb.AppendLine();

        foreach (var route in routes)
        {
            var actionName = RouteHelpers.ToCamelCase(route.Action);
            var hasParams = route.Parameters.Count > 0;

            sb.AppendLine(
                $"/** @controller {route.Controller} @action {route.Action} @route '{route.Url}' @method {route.Method} */"
            );

            if (hasParams)
            {
                var argsType = string.Join(
                    "; ",
                    route.Parameters.Select(p =>
                    {
                        var optional = route.Url.Contains($"{{{p}?}}") ? "?" : "";
                        return $"{p}{optional}: string | number";
                    })
                );
                var urlTemplate = RouteHelpers.BuildUrlTemplate(route);
                sb.AppendLine(
                    $"export const {actionName} = (args: {{ {argsType} }}): RouteDefinition<'{route.Method}'> => ({{"
                );
                sb.AppendLine($"    url: `{urlTemplate}`,");
            }
            else
            {
                sb.AppendLine(
                    $"export const {actionName} = (): RouteDefinition<'{route.Method}'> => ({{"
                );
                sb.AppendLine($"    url: '{route.Url}',");
            }
            sb.AppendLine($"    method: '{route.Method}',");
            sb.AppendLine($"}})");
            sb.AppendLine();

            if (hasParams)
            {
                var argsType = string.Join(
                    "; ",
                    route.Parameters.Select(p =>
                    {
                        var optional = route.Url.Contains($"{{{p}?}}") ? "?" : "";
                        return $"{p}{optional}: string | number";
                    })
                );
                sb.AppendLine(
                    $"{actionName}.url = (args: {{ {argsType} }}) => `{RouteHelpers.BuildUrlTemplate(route)}`"
                );
            }
            else
            {
                sb.AppendLine($"{actionName}.url = () => '{route.Url}'");
            }
            sb.AppendLine();
        }

        if (childDirs.Count > 0)
        {
            sb.AppendLine("// Sub-routes");
            foreach (var childDir in childDirs)
            {
                var childName = childDir.Split('/').Last();
                var importName = RouteHelpers.ToCamelCase(
                    childName
                        .Replace("-", " ")
                        .Split(' ')
                        .Aggregate((a, b) => a + char.ToUpper(b[0]) + b[1..])
                );
                sb.AppendLine($"export * as {importName} from './{childName}'");
            }
            sb.AppendLine();
        }

        return sb.ToString();
    }

    private static bool IsDirectChild(string parent, string candidate)
    {
        if (string.IsNullOrEmpty(parent))
            return !candidate.Contains('/') && candidate.Length > 0;

        return candidate.StartsWith(parent + "/")
            && !candidate[(parent.Length + 1)..].Contains('/');
    }
}
