/**
 * Auto-generated route helpers — do not edit.
 * Generated by Innovation.TsGen
 */

export interface RouteDefinition<M extends string = string> {
    url: string;
    method: M;
}

/** @controller Challenge @action advance @route '/api/v1/challenges/{id}/advance' @method post */
export const advance = (args: { id: string | number }): RouteDefinition<'post'> => ({
    url: `/api/v1/challenges/${args.id}/advance`,
    method: 'post',
})

advance.url = (args: { id: string | number }) => `/api/v1/challenges/${args.id}/advance`

