// <auto-generated />
using System;
using Innovation.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Innovation.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Innovation.Domain.Entities.Authorization.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GuardName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(125)
                        .HasColumnType("character varying(125)")
                        .HasDefaultValue("web");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("permissions", (string)null);
                });

            modelBuilder.Entity("Innovation.Domain.Entities.Authorization.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GuardName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(125)
                        .HasColumnType("character varying(125)")
                        .HasDefaultValue("web");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(125)
                        .HasColumnType("character varying(125)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("Innovation.Domain.Entities.Authorization.RolePermission", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<int>("PermissionId")
                        .HasColumnType("integer");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("role_has_permissions", (string)null);
                });

            modelBuilder.Entity("Innovation.Domain.Entities.Authorization.UserPermission", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("PermissionId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("model_has_permissions", (string)null);
                });

            modelBuilder.Entity("Innovation.Domain.Entities.Authorization.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("model_has_roles", (string)null);
                });

            modelBuilder.Entity("Innovation.Domain.Entities.Challenge.Challenge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AutoTransitionEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("AutomationSettings")
                        .HasColumnType("jsonb");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Difficulty")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("EnableComments")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EvaluationEndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EvaluationStartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Featured")
                        .HasColumnType("boolean");

                    b.Property<int?>("InnovationTypeId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<string>("Language")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int?>("MaxParticipants")
                        .HasColumnType("integer");

                    b.Property<int?>("MinEvaluatorsPerIdea")
                        .HasColumnType("integer");

                    b.Property<string>("ParticipationType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PublicUlid")
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("SubmissionDeadline")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SubmissionType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("TeamSizeMax")
                        .HasColumnType("integer");

                    b.Property<int?>("TeamSizeMin")
                        .HasColumnType("integer");

                    b.Property<int?>("TemplateId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Urgent")
                        .HasColumnType("boolean");

                    b.Property<string>("WinnerSelectionMethod")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("WinnersAnnouncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Featured");

                    b.HasIndex("InnovationTypeId");

                    b.HasIndex("PublicUlid")
                        .IsUnique()
                        .HasFilter("\"PublicUlid\" IS NOT NULL");

                    b.HasIndex("Status");

                    b.ToTable("challenges", (string)null);
                });

            modelBuilder.Entity("Innovation.Domain.Entities.Challenge.ChallengeAward", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AwardType")
                        .HasColumnType("text");

                    b.Property<int>("ChallengeId")
                        .HasColumnType("integer");

                    b.Property<string>("Color")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Icon")
                        .HasColumnType("text");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("Value")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.HasKey("Id");

                    b.HasIndex("ChallengeId");

                    b.ToTable("challenge_awards", (string)null);
                });

            modelBuilder.Entity("Innovation.Domain.Entities.Challenge.ChallengeGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("challenge_groups", (string)null);
                });

            modelBuilder.Entity("Innovation.Domain.Entities.Challenge.ChallengeIntellectualProperty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChallengeId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IpStatus")
                        .HasColumnType("text");

                    b.Property<string>("IpType")
                        .HasColumnType("text");

                    b.Property<string>("LicenseType")
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("OwnershipTerms")
                        .HasColumnType("text");

                    b.Property<string>("ProtectionMechanism")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ChallengeId")
                        .IsUnique();

                    b.ToTable("challenge_intellectual_properties", (string)null);
                });

            modelBuilder.Entity("Innovation.Domain.Entities.Challenge.ChallengeObjective", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChallengeId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Metrics")
                        .HasColumnType("jsonb");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ChallengeId");

                    b.ToTable("challenge_objectives", (string)null);
                });

            modelBuilder.Entity("Innovation.Domain.Entities.Challenge.ChallengeRequirement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChallengeId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Mandatory")
                        .HasColumnType("boolean");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<string>("Priority")
                        .HasColumnType("text");

                    b.Property<string>("RequirementType")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ChallengeId");

                    b.ToTable("challenge_requirements", (string)null);
                });

            modelBuilder.Entity("Innovation.Domain.Entities.Challenge.ChallengeRisk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChallengeId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Impact")
                        .HasColumnType("text");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<int?>("OwnerId")
                        .HasColumnType("integer");

                    b.Property<string>("Probability")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ChallengeId");

                    b.HasIndex("OwnerId");

                    b.ToTable("challenge_risks", (string)null);
                });

            modelBuilder.Entity("Innovation.Domain.Entities.Challenge.ChallengeSponsor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChallengeId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("ContributionAmount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<string>("SponsorName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("SponsorshipType")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WebsiteUrl")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ChallengeId");

                    b.ToTable("challenge_sponsors", (string)null);
                });

            modelBuilder.Entity("Innovation.Domain.Entities.Challenge.ChallengeSustainabilityImpact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChallengeId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("QuantifiableMetrics")
                        .HasColumnType("jsonb");

                    b.Property<string>("SdgAlignment")
                        .HasColumnType("jsonb");

                    b.Property<string>("Timeline")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ChallengeId")
                        .IsUnique();

                    b.ToTable("challenge_sustainability_impacts", (string)null);
                });

            modelBuilder.Entity("Innovation.Domain.Entities.Challenge.ChallengeTimeline", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChallengeId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Deliverables")
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("MilestoneEndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("MilestoneStartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ChallengeId");

                    b.ToTable("challenge_timelines", (string)null);
                });

            modelBuilder.Entity("Innovation.Domain.Entities.Challenge.ChallengeUser", b =>
                {
                    b.Property<int>("ChallengeId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("Role")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ChallengeId", "UserId", "Role");

                    b.HasIndex("UserId");

                    b.ToTable("challenge_users", (string)null);
                });

            modelBuilder.Entity("Innovation.Domain.Entities.InnovationType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Icon")
                        .HasColumnType("text");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("innovation_types", (string)null);
                });

            modelBuilder.Entity("Innovation.Domain.Entities.Lookup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Icon")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Type");

                    b.ToTable("lookups", (string)null);
                });

            modelBuilder.Entity("Innovation.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("KeycloakId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("KeycloakId")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Innovation.Domain.Entities.Authorization.RolePermission", b =>
                {
                    b.HasOne("Innovation.Domain.Entities.Authorization.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Innovation.Domain.Entities.Authorization.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Innovation.Domain.Entities.Authorization.UserPermission", b =>
                {
                    b.HasOne("Innovation.Domain.Entities.Authorization.Permission", "Permission")
                        .WithMany("UserPermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Innovation.Domain.Entities.User", "User")
                        .WithMany("UserPermissions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Innovation.Domain.Entities.Authorization.UserRole", b =>
                {
                    b.HasOne("Innovation.Domain.Entities.Authorization.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Innovation.Domain.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Innovation.Domain.Entities.Challenge.Challenge", b =>
                {
                    b.HasOne("Innovation.Domain.Entities.Lookup", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Innovation.Domain.Entities.InnovationType", "InnovationType")
                        .WithMany()
                        .HasForeignKey("InnovationTypeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.OwnsOne("Innovation.Domain.TranslatableString", "Description", b1 =>
                        {
                            b1.Property<int>("ChallengeId");

                            b1.Property<string>("Ar");

                            b1.Property<string>("En");

                            b1.HasKey("ChallengeId");

                            b1.ToTable("challenges");

                            b1
                                .ToJson("Description")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("ChallengeId");
                        });

                    b.OwnsOne("Innovation.Domain.TranslatableString", "Location", b1 =>
                        {
                            b1.Property<int>("ChallengeId");

                            b1.Property<string>("Ar");

                            b1.Property<string>("En");

                            b1.HasKey("ChallengeId");

                            b1.ToTable("challenges");

                            b1
                                .ToJson("Location")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("ChallengeId");
                        });

                    b.OwnsOne("Innovation.Domain.TranslatableString", "Organizer", b1 =>
                        {
                            b1.Property<int>("ChallengeId");

                            b1.Property<string>("Ar");

                            b1.Property<string>("En");

                            b1.HasKey("ChallengeId");

                            b1.ToTable("challenges");

                            b1
                                .ToJson("Organizer")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("ChallengeId");
                        });

                    b.OwnsOne("Innovation.Domain.TranslatableString", "Slug", b1 =>
                        {
                            b1.Property<int>("ChallengeId");

                            b1.Property<string>("Ar");

                            b1.Property<string>("En");

                            b1.HasKey("ChallengeId");

                            b1.ToTable("challenges");

                            b1
                                .ToJson("Slug")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("ChallengeId");
                        });

                    b.OwnsOne("Innovation.Domain.TranslatableString", "Title", b1 =>
                        {
                            b1.Property<int>("ChallengeId");

                            b1.Property<string>("Ar");

                            b1.Property<string>("En");

                            b1.HasKey("ChallengeId");

                            b1.ToTable("challenges");

                            b1
                                .ToJson("Title")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("ChallengeId");
                        });

                    b.Navigation("Category");

                    b.Navigation("Description")
                        .IsRequired();

                    b.Navigation("InnovationType");

                    b.Navigation("Location");

                    b.Navigation("Organizer");

                    b.Navigation("Slug")
                        .IsRequired();

                    b.Navigation("Title")
                        .IsRequired();
                });

            modelBuilder.Entity("Innovation.Domain.Entities.Challenge.ChallengeAward", b =>
                {
                    b.HasOne("Innovation.Domain.Entities.Challenge.Challenge", "Challenge")
                        .WithMany("Awards")
                        .HasForeignKey("ChallengeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Innovation.Domain.TranslatableString", "Description", b1 =>
                        {
                            b1.Property<int>("ChallengeAwardId");

                            b1.Property<string>("Ar");

                            b1.Property<string>("En");

                            b1.HasKey("ChallengeAwardId");

                            b1.ToTable("challenge_awards");

                            b1
                                .ToJson("Description")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("ChallengeAwardId");
                        });

                    b.OwnsOne("Innovation.Domain.TranslatableString", "Name", b1 =>
                        {
                            b1.Property<int>("ChallengeAwardId");

                            b1.Property<string>("Ar");

                            b1.Property<string>("En");

                            b1.HasKey("ChallengeAwardId");

                            b1.ToTable("challenge_awards");

                            b1
                                .ToJson("Name")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("ChallengeAwardId");
                        });

                    b.Navigation("Challenge");

                    b.Navigation("Description");

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("Innovation.Domain.Entities.Challenge.ChallengeIntellectualProperty", b =>
                {
                    b.HasOne("Innovation.Domain.Entities.Challenge.Challenge", "Challenge")
                        .WithOne("IntellectualProperty")
                        .HasForeignKey("Innovation.Domain.Entities.Challenge.ChallengeIntellectualProperty", "ChallengeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Challenge");
                });

            modelBuilder.Entity("Innovation.Domain.Entities.Challenge.ChallengeObjective", b =>
                {
                    b.HasOne("Innovation.Domain.Entities.Challenge.Challenge", "Challenge")
                        .WithMany("Objectives")
                        .HasForeignKey("ChallengeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Innovation.Domain.TranslatableString", "Description", b1 =>
                        {
                            b1.Property<int>("ChallengeObjectiveId");

                            b1.Property<string>("Ar");

                            b1.Property<string>("En");

                            b1.HasKey("ChallengeObjectiveId");

                            b1.ToTable("challenge_objectives");

                            b1
                                .ToJson("Description")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("ChallengeObjectiveId");
                        });

                    b.OwnsOne("Innovation.Domain.TranslatableString", "ExpectedOutcome", b1 =>
                        {
                            b1.Property<int>("ChallengeObjectiveId");

                            b1.Property<string>("Ar");

                            b1.Property<string>("En");

                            b1.HasKey("ChallengeObjectiveId");

                            b1.ToTable("challenge_objectives");

                            b1
                                .ToJson("ExpectedOutcome")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("ChallengeObjectiveId");
                        });

                    b.OwnsOne("Innovation.Domain.TranslatableString", "Objective", b1 =>
                        {
                            b1.Property<int>("ChallengeObjectiveId");

                            b1.Property<string>("Ar");

                            b1.Property<string>("En");

                            b1.HasKey("ChallengeObjectiveId");

                            b1.ToTable("challenge_objectives");

                            b1
                                .ToJson("Objective")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("ChallengeObjectiveId");
                        });

                    b.Navigation("Challenge");

                    b.Navigation("Description");

                    b.Navigation("ExpectedOutcome");

                    b.Navigation("Objective")
                        .IsRequired();
                });

            modelBuilder.Entity("Innovation.Domain.Entities.Challenge.ChallengeRequirement", b =>
                {
                    b.HasOne("Innovation.Domain.Entities.Challenge.Challenge", "Challenge")
                        .WithMany("Requirements")
                        .HasForeignKey("ChallengeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Innovation.Domain.TranslatableString", "Description", b1 =>
                        {
                            b1.Property<int>("ChallengeRequirementId");

                            b1.Property<string>("Ar");

                            b1.Property<string>("En");

                            b1.HasKey("ChallengeRequirementId");

                            b1.ToTable("challenge_requirements");

                            b1
                                .ToJson("Description")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("ChallengeRequirementId");
                        });

                    b.OwnsOne("Innovation.Domain.TranslatableString", "Requirement", b1 =>
                        {
                            b1.Property<int>("ChallengeRequirementId");

                            b1.Property<string>("Ar");

                            b1.Property<string>("En");

                            b1.HasKey("ChallengeRequirementId");

                            b1.ToTable("challenge_requirements");

                            b1
                                .ToJson("Requirement")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("ChallengeRequirementId");
                        });

                    b.Navigation("Challenge");

                    b.Navigation("Description");

                    b.Navigation("Requirement")
                        .IsRequired();
                });

            modelBuilder.Entity("Innovation.Domain.Entities.Challenge.ChallengeRisk", b =>
                {
                    b.HasOne("Innovation.Domain.Entities.Challenge.Challenge", "Challenge")
                        .WithMany("Risks")
                        .HasForeignKey("ChallengeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Innovation.Domain.Entities.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.OwnsOne("Innovation.Domain.TranslatableString", "Description", b1 =>
                        {
                            b1.Property<int>("ChallengeRiskId");

                            b1.Property<string>("Ar");

                            b1.Property<string>("En");

                            b1.HasKey("ChallengeRiskId");

                            b1.ToTable("challenge_risks");

                            b1
                                .ToJson("Description")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("ChallengeRiskId");
                        });

                    b.OwnsOne("Innovation.Domain.TranslatableString", "MitigationStrategy", b1 =>
                        {
                            b1.Property<int>("ChallengeRiskId");

                            b1.Property<string>("Ar");

                            b1.Property<string>("En");

                            b1.HasKey("ChallengeRiskId");

                            b1.ToTable("challenge_risks");

                            b1
                                .ToJson("MitigationStrategy")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("ChallengeRiskId");
                        });

                    b.OwnsOne("Innovation.Domain.TranslatableString", "RiskName", b1 =>
                        {
                            b1.Property<int>("ChallengeRiskId");

                            b1.Property<string>("Ar");

                            b1.Property<string>("En");

                            b1.HasKey("ChallengeRiskId");

                            b1.ToTable("challenge_risks");

                            b1
                                .ToJson("RiskName")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("ChallengeRiskId");
                        });

                    b.Navigation("Challenge");

                    b.Navigation("Description");

                    b.Navigation("MitigationStrategy");

                    b.Navigation("Owner");

                    b.Navigation("RiskName")
                        .IsRequired();
                });

            modelBuilder.Entity("Innovation.Domain.Entities.Challenge.ChallengeSponsor", b =>
                {
                    b.HasOne("Innovation.Domain.Entities.Challenge.Challenge", "Challenge")
                        .WithMany("Sponsors")
                        .HasForeignKey("ChallengeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Challenge");
                });

            modelBuilder.Entity("Innovation.Domain.Entities.Challenge.ChallengeSustainabilityImpact", b =>
                {
                    b.HasOne("Innovation.Domain.Entities.Challenge.Challenge", "Challenge")
                        .WithOne("SustainabilityImpact")
                        .HasForeignKey("Innovation.Domain.Entities.Challenge.ChallengeSustainabilityImpact", "ChallengeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Innovation.Domain.TranslatableString", "Description", b1 =>
                        {
                            b1.Property<int>("ChallengeSustainabilityImpactId");

                            b1.Property<string>("Ar");

                            b1.Property<string>("En");

                            b1.HasKey("ChallengeSustainabilityImpactId");

                            b1.ToTable("challenge_sustainability_impacts");

                            b1
                                .ToJson("Description")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("ChallengeSustainabilityImpactId");
                        });

                    b.OwnsOne("Innovation.Domain.TranslatableString", "ImpactArea", b1 =>
                        {
                            b1.Property<int>("ChallengeSustainabilityImpactId");

                            b1.Property<string>("Ar");

                            b1.Property<string>("En");

                            b1.HasKey("ChallengeSustainabilityImpactId");

                            b1.ToTable("challenge_sustainability_impacts");

                            b1
                                .ToJson("ImpactArea")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("ChallengeSustainabilityImpactId");
                        });

                    b.Navigation("Challenge");

                    b.Navigation("Description");

                    b.Navigation("ImpactArea");
                });

            modelBuilder.Entity("Innovation.Domain.Entities.Challenge.ChallengeTimeline", b =>
                {
                    b.HasOne("Innovation.Domain.Entities.Challenge.Challenge", "Challenge")
                        .WithMany("Timeline")
                        .HasForeignKey("ChallengeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Innovation.Domain.TranslatableString", "Description", b1 =>
                        {
                            b1.Property<int>("ChallengeTimelineId");

                            b1.Property<string>("Ar");

                            b1.Property<string>("En");

                            b1.HasKey("ChallengeTimelineId");

                            b1.ToTable("challenge_timelines");

                            b1
                                .ToJson("Description")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("ChallengeTimelineId");
                        });

                    b.OwnsOne("Innovation.Domain.TranslatableString", "MilestoneName", b1 =>
                        {
                            b1.Property<int>("ChallengeTimelineId");

                            b1.Property<string>("Ar");

                            b1.Property<string>("En");

                            b1.HasKey("ChallengeTimelineId");

                            b1.ToTable("challenge_timelines");

                            b1
                                .ToJson("MilestoneName")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("ChallengeTimelineId");
                        });

                    b.Navigation("Challenge");

                    b.Navigation("Description");

                    b.Navigation("MilestoneName")
                        .IsRequired();
                });

            modelBuilder.Entity("Innovation.Domain.Entities.Challenge.ChallengeUser", b =>
                {
                    b.HasOne("Innovation.Domain.Entities.Challenge.Challenge", "Challenge")
                        .WithMany("ChallengeUsers")
                        .HasForeignKey("ChallengeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Innovation.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Challenge");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Innovation.Domain.Entities.InnovationType", b =>
                {
                    b.OwnsOne("Innovation.Domain.TranslatableString", "Description", b1 =>
                        {
                            b1.Property<int>("InnovationTypeId");

                            b1.Property<string>("Ar");

                            b1.Property<string>("En");

                            b1.HasKey("InnovationTypeId");

                            b1.ToTable("innovation_types");

                            b1
                                .ToJson("Description")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("InnovationTypeId");
                        });

                    b.OwnsOne("Innovation.Domain.TranslatableString", "Name", b1 =>
                        {
                            b1.Property<int>("InnovationTypeId");

                            b1.Property<string>("Ar");

                            b1.Property<string>("En");

                            b1.HasKey("InnovationTypeId");

                            b1.ToTable("innovation_types");

                            b1
                                .ToJson("Name")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("InnovationTypeId");
                        });

                    b.Navigation("Description");

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("Innovation.Domain.Entities.Lookup", b =>
                {
                    b.OwnsOne("Innovation.Domain.TranslatableString", "Description", b1 =>
                        {
                            b1.Property<int>("LookupId");

                            b1.Property<string>("Ar");

                            b1.Property<string>("En");

                            b1.HasKey("LookupId");

                            b1.ToTable("lookups");

                            b1
                                .ToJson("Description")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("LookupId");
                        });

                    b.OwnsOne("Innovation.Domain.TranslatableString", "Name", b1 =>
                        {
                            b1.Property<int>("LookupId");

                            b1.Property<string>("Ar");

                            b1.Property<string>("En");

                            b1.HasKey("LookupId");

                            b1.ToTable("lookups");

                            b1
                                .ToJson("Name")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("LookupId");
                        });

                    b.Navigation("Description");

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("Innovation.Domain.Entities.Authorization.Permission", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserPermissions");
                });

            modelBuilder.Entity("Innovation.Domain.Entities.Authorization.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Innovation.Domain.Entities.Challenge.Challenge", b =>
                {
                    b.Navigation("Awards");

                    b.Navigation("ChallengeUsers");

                    b.Navigation("IntellectualProperty");

                    b.Navigation("Objectives");

                    b.Navigation("Requirements");

                    b.Navigation("Risks");

                    b.Navigation("Sponsors");

                    b.Navigation("SustainabilityImpact");

                    b.Navigation("Timeline");
                });

            modelBuilder.Entity("Innovation.Domain.Entities.User", b =>
                {
                    b.Navigation("UserPermissions");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
