apiVersion: v1
kind: Secret
metadata:
  name: innovation-secrets
  namespace: innovation
type: Opaque
stringData:
  postgres-password: "PG_PWD_PLACEHOLDER"
  redis-password: "REDIS_PWD_PLACEHOLDER"
  keycloak-password: "KC_PWD_PLACEHOLDER"
  ldap-admin-password: "LDAP_PWD_PLACEHOLDER"
